export { default as Home } from './Home'
export { default as Layout } from './Layout'
export { default as Error } from './Error'
export { default as About } from './About'
export { default as Shop } from './Shop'
export { default as SingleProduct } from './SingleProduct'
