import image1 from './assets/images/e-book icon.png'

export const products = [
  {
    productImage: image1,
    productName: 'E-book 1',
    productRatings: 3,
    productPrice: 20000,
    category: 'equipment',
    topRated: true,
    productColor: 'Blue',
    productBrand: 'Beforemath',
    sale: true,
    discountPrice: 18000,
  },
  {
    productImage: image1,
    productName: 'E-book 2',
    productRatings: 4,
    productPrice: 50000,
    category: 'equipment',
    topRated: true,
    productColor: 'Red',
    productBrand: 'Beforemath',
    sale: true,
    discountPrice: 18000,
  },
  {
    productImage: image1,
    productName: 'E-book 3',
    productRatings: 4,
    productPrice: 6000,
    category: 'nutrition',
    topRated: true,
    productColor: 'Red',
    productBrand: 'Beforemath',
  },
  {
    productImage: image1,
    productName: 'E-book 4',
    productRatings: 4,
    productPrice: 2000,
    category: 'nutrition',
    topRated: true,
    productColor: 'Red',
    productBrand: 'Beforemath',
  },
  {
    productImage: image1,
    productName: 'E-book 5',
    productRatings: 4,
    productPrice: 20000,
    category: 'nutrition',
    topRated: false,
    productColor: 'Red',
    productBrand: 'Beforemath',
    sale: true,
    discountPrice: 18000,
  },
  {
    productImage: image1,
    productName: 'E-book 6',
    productPrice: 25000,
    category: 'nutrition',
    topRated: false,
    productColor: 'Red',
    productBrand: 'Humane Labs Raid',
  },
  {
    productImage: image1,
    productName: 'E-book 7',
    productRatings: 4,
    productPrice: 2000,
    category: 'nutrition',
    topRated: false,
    productColor: 'Red',
    productBrand: 'Beforemath',
  },
  {
    productImage: image1,
    productName: 'E-book 8',
    productRatings: 4,
    productPrice: 2000,
    category: 'nutrition',
    topRated: false,
    productColor: 'Red',
    productBrand: 'Beforemath',
  },
  {
    productImage: image1,
    productName: 'E-book 9',
    productRatings: 4,
    productPrice: 2000,
    category: 'nutrition',
    topRated: false,
    productColor: 'Red',
    productBrand: 'Beforemath',
  },
  {
    productImage: image1,
    productName: 'E-book 10',
    productRatings: 4,
    productPrice: 2000,
    category: 'nutrition',
    topRated: false,
    productColor: 'Red',
    productBrand: 'Beforemath',
    sale: true,
    discountPrice: 18000,
  },
  {
    productImage: image1,
    productName: 'E-book 11',
    productRatings: 4,
    productPrice: 2000,
    category: 'nutrition',
    topRated: false,
    productColor: 'Red',
    productBrand: 'Beforemath',
  },
]
